services:
  db:
    image: postgres:15-alpine
    container_name: rbs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    #ports:
    #  - "5432:5432"   # опционально
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    # env_file:  -- удаляем, потому что файл data.env уже скопирован в образ

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: